name: 'Nx affected dependencies action'
description: 'Run angular CLI commands for an affected project and all its affected dependencies'
author: 'LeanIX GmbH'
inputs:
  project:
    required: true
    description: 'The name of the project whose affected dependencies you want to lint/test etc..'
  target:
    required: true
    description: "The angular CLI target you want to execute, e.g. 'lint' or 'test'."
  base:
    required: false
    description: 'The base reference to be used for the affected evaluation.'
  head:
    required: false
    description: 'The head reference to be used for the affected evaluation.'
  gitflow:
    required: false
    description: "Set to 'true' for this action to automatically compare the merge commit to the previous one on develop/master and to use origin/develop as base when running on a feature branch."
  runner:
    required: false
    description: 'The runner of the command. Used to leverage nx cache.'
outputs:
  isAffected:
    description: 'Indicates if the provided project is affected'
  affectedDeps:
    description: 'List of affected project and its affected dependencies concatenated with comma.'
runs:
  using: 'node12'
  main: 'dist/index.js'
